In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from scipy.stats import multivariate_normal

In [3]:
def create_data():
    iris = load_iris()
    df = pd.DataFrame(iris.data, columns=iris.feature_names)
    df['label'] = iris.target
    df.columns = ['sepal length', 'sepal width', 'petal length', 'petal width', 'label']
    data = np.array(df.iloc[:150, [0, 1, 2,-1]])
    return data[:,:3], data[:,-1]

In [4]:
X, y = create_data()

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y,  test_size=0.2, random_state=42)

In [6]:
p_y1 = np.sum(y_train ==1 )/y_train.shape[0]
p_y2 = np.sum(y_train ==2 )/y_train.shape[0]
p_y0 = 1-p_y1-p_y2

In [7]:
X_son = X_train[np.where(y_train==0)[0]]

In [8]:
print(X_son)

[[4.6 3.6 1. ]
 [5.7 4.4 1.5]
 [4.8 3.4 1.6]
 [4.4 3.2 1.3]
 [5.2 3.5 1.5]
 [5.  3.6 1.4]
 [5.2 4.1 1.5]
 [5.4 3.9 1.3]
 [5.4 3.7 1.5]
 [5.1 3.5 1.4]
 [5.2 3.4 1.4]
 [5.  3.5 1.3]
 [5.1 3.8 1.9]
 [4.8 3.4 1.9]
 [5.  3.  1.6]
 [5.1 3.3 1.7]
 [5.1 3.4 1.5]
 [4.6 3.2 1.4]
 [5.5 4.2 1.4]
 [5.4 3.9 1.7]
 [5.  3.3 1.4]
 [5.  3.2 1.2]
 [4.9 3.1 1.5]
 [5.  3.4 1.5]
 [5.  3.5 1.6]
 [4.4 2.9 1.4]
 [4.3 3.  1.1]
 [4.6 3.1 1.5]
 [5.1 3.5 1.4]
 [4.4 3.  1.3]
 [4.6 3.4 1.4]
 [4.7 3.2 1.3]
 [5.1 3.8 1.6]
 [4.5 2.3 1.3]
 [5.3 3.7 1.5]
 [5.1 3.7 1.5]
 [4.9 3.1 1.5]
 [4.9 3.  1.4]
 [5.4 3.4 1.7]
 [5.8 4.  1.2]]


In [9]:
mu_0 = np.mean(X_son,axis=0)
mu_0

array([4.99  , 3.44  , 1.4525])

In [10]:
sigma_0 = np.var(X_son,axis=0)
sigma_0

array([0.1239    , 0.1549    , 0.03299375])

In [11]:
P_X0 = multivariate_normal.pdf(X_test,mean=mu_0,cov=sigma_0)*p_y0

In [12]:
P_X0

array([6.04542330e-073, 2.86094444e-002, 5.72427122e-210, 4.02218912e-064,
       7.22160750e-081, 4.10324212e-001, 3.24931405e-032, 6.42103952e-095,
       1.20114984e-066, 3.82496601e-042, 1.93406387e-092, 3.73270511e-001,
       2.04584806e-001, 5.41666376e-001, 5.09442899e-001, 3.01919472e-073,
       1.83081574e-129, 4.06764596e-042, 2.20488373e-063, 4.50312620e-118,
       3.57687022e-001, 1.86915106e-081, 6.01485962e-001, 4.50312620e-118,
       6.34503586e-177, 1.25935929e-098, 1.46787881e-131, 8.30437878e-137,
       3.73270511e-001, 3.60014895e-001])

In [13]:
X_son_1 = X_train[np.where(y_train==1)[0]]

In [14]:
X_son_2 = X_train[np.where(y_train==2)[0]]

In [15]:
mu_1 = np.mean(X_son_1,axis=0)

In [16]:
mu_2 = np.mean(X_son_2,axis=0)

In [17]:
sigma_1 = np.var(X_son_1,axis=0)

In [18]:
sigma_2 = np.var(X_son_2,axis=0)

In [19]:
P_X1 = multivariate_normal.pdf(X_test,mean=mu_1,cov=sigma_1)*p_y1

In [20]:
P_X1

array([1.59077128e-01, 7.68652395e-10, 1.48678722e-10, 2.11283877e-01,
       3.48152531e-02, 1.38328819e-09, 8.33958871e-02, 5.73972806e-03,
       3.98098132e-02, 1.97929773e-01, 1.16653561e-02, 4.02453339e-10,
       6.67567717e-11, 1.52142698e-09, 2.50054450e-11, 3.24338233e-02,
       5.31793391e-04, 1.20765488e-01, 2.12661088e-01, 3.01395690e-03,
       1.57185683e-09, 7.49284252e-02, 1.67060185e-09, 3.01395690e-03,
       4.83423930e-11, 9.37246101e-03, 2.98391676e-04, 6.29609697e-05,
       4.02453339e-10, 3.45098998e-09])

In [21]:
P_X2 = multivariate_normal.pdf(X_test,mean=mu_2,cov=sigma_2)*p_y2

In [22]:
P_X2

array([4.05777134e-02, 2.00908322e-14, 6.73740180e-04, 2.13393116e-02,
       6.11242982e-02, 8.19162427e-15, 1.02755355e-04, 1.08453769e-01,
       1.38650101e-03, 7.02849215e-04, 1.05788627e-01, 6.41133365e-16,
       3.64764330e-16, 3.66966070e-15, 2.52523797e-16, 3.12804465e-02,
       1.64539982e-01, 2.24843620e-04, 1.15973617e-02, 1.59860170e-01,
       5.32601251e-15, 7.68632263e-02, 9.13796497e-15, 1.59860170e-01,
       1.57127015e-04, 1.52638585e-01, 5.34354623e-02, 1.03013280e-01,
       6.41133365e-16, 9.83162709e-15])

In [23]:
a = np.vstack((P_X0,P_X1,P_X2))
a

array([[6.04542330e-073, 2.86094444e-002, 5.72427122e-210,
        4.02218912e-064, 7.22160750e-081, 4.10324212e-001,
        3.24931405e-032, 6.42103952e-095, 1.20114984e-066,
        3.82496601e-042, 1.93406387e-092, 3.73270511e-001,
        2.04584806e-001, 5.41666376e-001, 5.09442899e-001,
        3.01919472e-073, 1.83081574e-129, 4.06764596e-042,
        2.20488373e-063, 4.50312620e-118, 3.57687022e-001,
        1.86915106e-081, 6.01485962e-001, 4.50312620e-118,
        6.34503586e-177, 1.25935929e-098, 1.46787881e-131,
        8.30437878e-137, 3.73270511e-001, 3.60014895e-001],
       [1.59077128e-001, 7.68652395e-010, 1.48678722e-010,
        2.11283877e-001, 3.48152531e-002, 1.38328819e-009,
        8.33958871e-002, 5.73972806e-003, 3.98098132e-002,
        1.97929773e-001, 1.16653561e-002, 4.02453339e-010,
        6.67567717e-011, 1.52142698e-009, 2.50054450e-011,
        3.24338233e-002, 5.31793391e-004, 1.20765488e-001,
        2.12661088e-001, 3.01395690e-003, 1.57185683e-0

In [24]:
np.argmax(a,axis=0)

array([1, 0, 2, 1, 2, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0], dtype=int32)

In [25]:
y_test

array([1., 0., 2., 1., 1., 0., 1., 2., 1., 1., 2., 0., 0., 0., 0., 1., 2.,
       1., 1., 2., 0., 2., 0., 2., 2., 2., 2., 2., 0., 0.])

In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=0)

In [27]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train, y_train)
MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [28]:
clf.score(X_train, y_train)

0.6916666666666667

In [29]:
clf.score(X_test, y_test)

0.5666666666666667